version: '3.4'

services:
  # App
  customerapp.restapi:
    image: ${DOCKER_REGISTRY-}customerapprestapi
    build:
      context: .
      dockerfile: src/CustomerApp.RestApi/Dockerfile
    ports:
    - 5000:80
  
  # Local SMTP server
  smtpdev:
    image: rnwood/smtp4dev
    container_name: smtpdev
    ports: 
    - 3000:80
    - 2525:25
    - 143:143

  # Mongo Database
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  # Mongo web-based admin interface
  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    restart: always
    depends_on:
    - mongo
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongo
